import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Crimson_Pro } from 'next/font/google';
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const crimson = Crimson_Pro({ 
  subsets: ['latin'], 
  variable: '--font-crimson' 
});


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Wiston & Co. Law Firm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimson.variable} ${montserrat.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
